export const profile = {
  name: 'Akshay Venkata Narayana',
  shortName: 'Akshay',
  role: 'Product & UX Designer',
  location: 'United Kingdom',
  email: 'akshayv2310@gmail.com',
  phone: '+44 7810120379',
  years: '5+',
  projects: '20+',
  clients: '10+',
};

export const experience = [
  {
    company: 'Free UK Genealogy',
    role: 'Volunteer UX Designer',
    place: 'United Kingdom',
    date: 'Jul 2026 — Present',
    summary: 'Supporting the user experience of a free, volunteer-powered family-history service.',
    contribution: 'Improving journeys, information structure and interface clarity across the service.',
  },
  {
    company: 'The View Magazine CIC',
    role: 'Volunteer UX/UI Designer',
    place: 'United Kingdom',
    date: 'Dec 2025 — Feb 2026',
    summary: 'A mobile-first magazine experience that makes current and archived issues easier to discover and read.',
    contribution: 'Information architecture, issue discovery, archive flow and responsive reading experience.',
  },
  {
    company: 'LUXTJ Website & Extranet',
    role: 'Contract UX/UI Designer',
    place: 'Remote',
    date: 'Aug 2025 — May 2026',
    summary: 'A connected luxury-travel website and partner extranet spanning discovery, booking and operations.',
    contribution: 'End-to-end product design across eight core modules, from flows and UI through developer handoff.',
  },
  {
    company: 'Proficon Labs',
    role: 'UX Designer',
    place: 'Hyderabad, India',
    date: 'Oct 2024 — Aug 2025',
    summary: 'Enterprise dashboards, CRM workflows and an AI-supported website-building product.',
    contribution: 'Simplified navigation, information-dense workflows and reusable interface patterns.',
  },
  {
    company: 'Halohues Studios',
    role: 'UX/UI Designer',
    place: 'Hyderabad, India',
    date: 'Jan 2024 — Oct 2024',
    summary: 'Responsive product experiences for client projects across web and mobile.',
    contribution: 'Wireframes, high-fidelity UI, component systems and developer-ready handoff.',
  },
  {
    company: 'LUXTJ Mobile Application',
    role: 'Freelance UX/UI Designer',
    place: 'Remote',
    date: 'Dec 2023 — Aug 2024',
    summary: 'A premium mobile journey for destination discovery, trip planning and booking.',
    contribution: 'Designed the discover → compare → save → book journey and its core interaction patterns.',
  },
  {
    company: 'Bratha (India) Private Limited',
    role: 'UX/UI Designer',
    place: 'Remote',
    date: 'Jul 2023 — Oct 2023',
    summary: 'A clearer, more consistent digital product experience across responsive breakpoints.',
    contribution: 'Product flows, visual design, reusable components and engineering handoff.',
  },
  {
    company: 'Astro Sutra',
    role: 'Freelance UX/UI Designer',
    place: 'Remote',
    date: 'Oct 2022 — Mar 2023',
    summary: 'A mobile platform for astrologer discovery and consultation booking.',
    contribution: 'Improved trust and clarity through profile structure, content hierarchy and focused actions.',
  },
  {
    company: 'Match Scope',
    role: 'Freelance UX/UI Designer',
    place: 'Remote',
    date: 'Jan 2022 — Jul 2022',
    summary: 'An astrology-based match-prediction journey from onboarding to compatibility results.',
    contribution: 'Turned complex inputs into step-by-step forms and easier-to-understand result screens.',
  },
];

export const capabilities = [
  'Product strategy',
  'User research',
  'Information architecture',
  'Interaction design',
  'Prototyping',
  'Design systems',
  'Usability testing',
  'Developer handoff',
];
