'use client';
import {useEffect,useRef} from 'react';
const skills=['Design systems','Experience design','Storytelling','User research','Problem solving','Strategy','Product design','AI tools'];
const quotes=[['Maya Chen','VP, Product','Alex makes complex products feel obvious. The final experience was sharp, human, and incredibly effective.'],['Jon Bell','Founder, Northstar','A strategic thinker with exceptional craft. Every decision came back to the user and the business.'],['Priya Shah','Head of Growth','The work changed how our team thinks about design — and lifted activation in the process.'],['Sam Wilson','CEO, Forma','Fast, thoughtful and deeply collaborative. Alex brought clarity to an ambiguous, high-stakes challenge.']];
export default function Home(){const root=useRef<HTMLElement>(null);useEffect(()=>{const n=root.current;if(!n)return;const o=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('is-visible')),{threshold:.12});n.querySelectorAll('.reveal').forEach(e=>o.observe(e));const m=(e:PointerEvent)=>{n.style.setProperty('--mx',`${(e.clientX/innerWidth-.5)*18}px`);n.style.setProperty('--my',`${(e.clientY/innerHeight-.5)*18}px`)};addEventListener('pointermove',m,{passive:true});return()=>{o.disconnect();removeEventListener('pointermove',m)}} ,[]);return <main ref={root}>
<nav className="nav shell"><div><strong>Based in</strong><span>London, UK</span></div><a className="pill dark-pill" href="#contact">Get in touch <b>↗</b></a></nav>
<section className="hero shell"><div className="hero-statement"><p className="hero-opener">Pretty screens are easy.</p><h1>Understanding <strong>why someone hesitates, what the system needs next, where the journey breaks and how everything connects</strong> is the real work.</h1><p className="hero-line">That&apos;s the part I design.</p><div className="hero-bottom"><p><strong>Product Designer working across complex digital systems.</strong></p><a className="hero-link" href="#work">See the thinking behind the pixels <b>↗</b></a></div></div><div className="portrait parallax"><img src="https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=800&q=88" alt="Alex Morgan, product designer"/><i>✦</i></div></section>
<section className="identity reveal"><span className="available"><i/> Open to select opportunities</span><div className="id-card"><img src="https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=160&q=80" alt=""/><div><strong>ALEX MORGAN</strong><small>Product Designer · UX Strategist</small></div><b>☰</b></div></section>
<section id="work" className="work shell reveal"><div className="section-kicker"><span>Selected case studies</span><a href="#work">All case studies ↗</a></div><article className="case-card"><div className="case-art"><div className="browser"><div className="browser-top"><i/><i/><i/></div><div className="browser-body"><aside/><div className="screen"><div className="screen-title"/><div className="trip-grid"><span/><span/><span/><span/></div></div></div></div></div><div className="case-copy"><div className="case-head"><b>CASE STUDY · 02</b><em>12 min read</em></div><div className="tags"><span>Product design</span><span>End to end</span><span>Web + Mobile</span></div><h2>LUXTJ — BRINGING LUXURY TRAVEL TO THE WEB</h2><p>A year-long, end-to-end redesign of a luxury travel platform — from research and product strategy to a polished booking experience.</p><a className="pill" href="#about">View case study <b>↗</b></a></div></article></section>
<section className="skills shell reveal"><div className="skills-center"><h3>What I bring to the table</h3><p>Ideas into experiences worth remembering.</p></div>{skills.map((s,i)=><span key={s} className={`skill s${i}`}>{s}</span>)}</section>
<section id="about" className="about shell reveal"><div className="about-copy"><span className="eyebrow">About me</span><h2>Designing with curiosity,<br/>clarity, and care.</h2><p>I&apos;m Alex — a product designer and UX strategist passionate about crafting meaningful digital experiences. I work where user needs, business goals, and elegant systems meet.</p><div className="stats"><div><b>5+</b><span>Years experience</span></div><div><b>24</b><span>Projects shipped</span></div><div><b>12</b><span>Happy clients</span></div></div><a className="pill outline" href="#contact">More about me <b>↗</b></a></div><div className="about-photo parallax"><img src="https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1100&q=85" alt="Designer exploring the landscape"/><span>Curious by nature ↗</span></div></section>
<section className="endorse shell reveal"><span className="eyebrow">Kind words</span><h2>Endorsed by industry leaders<br/>and brilliant collaborators.</h2><div className="quote-grid">{quotes.map(([n,r,q])=><article className="quote" key={n}><b>★★★★★</b><p>{q}</p><div><span>{n}</span><small>{r}</small></div></article>)}<article className="metric dark"><small>Average client satisfaction</small><strong>98%</strong><span>Across 12 engagements</span></article><article className="metric"><small>Growth after redesign</small><strong>2.4×</strong><span>Median product impact</span></article></div></section>
<section id="contact" className="contact shell reveal"><div><span>LET&apos;S CONNECT</span><h2>Have a product idea<br/>or design challenge?</h2></div><div><p>I&apos;m open to product design roles, UX projects, and meaningful collaborations.</p><a className="pill" href="mailto:hello@alexmorgan.design">Say hello <b>↗</b></a></div></section><footer className="shell">© 2026 ALEX MORGAN — PRODUCT DESIGNER / UX STRATEGIST <a href="#">Back to top ↑</a></footer>
</main>}
