import type {Metadata} from 'next';

export const metadata:Metadata={title:'LUXTJ Case Study — Akshay Venkata Narayana',description:'An end-to-end product design case study bringing the LUXTJ luxury travel experience to the web.'};

const overview=[['Year','2025'],['Role','Sole Designer'],['Timeline','12 months'],['Status','Live at luxtj.com']];
const responsibilities=[['Product thinking','Translated LUXTJ’s product model from mobile to web, identifying opportunities to improve discovery, planning and booking.'],['Information architecture','Structured destinations, search, hotels, flights, Bucket List and Travel Calendar into a connected experience.'],['UX & interaction design','Designed end-to-end flows, filters, selection patterns, booking journeys, information states and edge cases.'],['UI & visual design','Created responsive layouts, hierarchy, reusable components and interaction states across platforms.'],['Validation & iteration','Reviewed flows, tested assumptions and refined interactions as requirements and constraints evolved.'],['Design → development','Worked with developers to communicate behaviour, review implementation and bring the work into production.']];

export default function LuxtjPage(){return <main className="subpage case-page">
  <header className="sub-nav shell"><a href="/"><strong>Based in</strong><span>United Kingdom</span></a><a className="pill dark-pill" href="/contact">Get in touch <b>↗</b></a></header>
  <section className="case-hero shell"><span>CASE STUDY · 01</span><h1>LuxTJ — bringing a luxury travel app to the web</h1><p>After designing LUXTJ&apos;s traveller mobile app, I expanded the product into two connected web experiences — a customer-facing travel platform and an extranet for property partners.</p>
    <div className="monitor-stage"><img className="monitor side left-monitor" src="/luxtj-side.png" alt="LUXTJ booking confirmation interface"/><img className="monitor main-monitor" src="/luxtj-main.png" alt="LUXTJ travel search interface"/><img className="monitor side right-monitor" src="/luxtj-side.png" alt="LUXTJ booking detail interface"/></div>
  </section>
  <section className="case-overview shell">{overview.map(([k,v])=><div key={k}><small>{k}</small><strong>{v}</strong></div>)}</section>
  <div className="case-body shell">
    <aside className="case-index"><a href="#challenge">Overview</a><a href="#opportunity">The opportunity</a><a href="#principle">Design principle</a><a href="#responsibility">My role</a><a href="#testing">Iterations</a><a href="#outcome">Outcome</a><a href="#learning">Learning</a></aside>
    <div className="case-story">
      <section id="challenge"><span>01 — The challenge</span><h2>The mobile experience worked. The web needed to work differently.</h2><p>Because I had already designed the mobile product, I understood LUXTJ&apos;s core features and the relationship between discovering somewhere to travel and turning that interest into a trip. But moving to web introduced a different set of behaviours.</p><p>Desktop travellers have more room to explore destinations, compare hotels and flights, revisit options and make considered decisions.</p><blockquote><small>The design question became</small>How might LUXTJ make discovering, planning and booking a complex trip feel more connected and effortless?</blockquote></section>
      <section id="opportunity"><span>02 — The product opportunity</span><h2>Connect inspiration with action.</h2><p>Travel doesn&apos;t always begin with a search or booking form. Someone might discover Japan through an article, save a resort in the Maldives, or keep a list of places they would like to visit someday.</p><div className="case-callout"><div><b>BUCKET LIST</b><p>Where would I love to go?</p></div><div><b>TRAVEL CALENDAR</b><p>When should I go?</p></div></div><strong className="journey">DISCOVER → SAVE → DECIDE WHEN → PLAN → BOOK</strong></section>
      <section id="principle"><span>03 — The design principle</span><h2>Don&apos;t design individual travel features. Design the journey between them.</h2><p>Flights, hotels, destinations, saved places and travel dates solve different problems. Travellers do not think about them as separate product modules. Every interaction should help someone discover, decide, or move their trip forward.</p></section>
      <section id="responsibility"><span>04 — What I was responsible for</span><h2>I owned the customer web experience end-to-end.</h2><div className="responsibility-list">{responsibilities.map(([title,body])=><article key={title}><b>{title}</b><p>{body}</p></article>)}</div></section>
      <section id="testing"><span>05 — Validation & iteration</span><h2>Test the uncertain parts on purpose.</h2><p>I ran moderated usability sessions with eight frequent international travellers to pressure-test the calendar and Bucket List. Testers treated the calendar as a list of upcoming trips rather than a grid of days, while playful progress mechanics in the first Bucket List iteration felt out of step with a luxury service.</p><div className="case-metrics"><div><b>8</b><small>Users tested</small></div><div><b>3+</b><small>Design iterations</small></div><div><b>2</b><small>Features refined</small></div></div></section>
      <section id="outcome"><span>06 — The outcome</span><h2>One connected product across mobile and web.</h2><p>The final experience replaces compact, swipe-first patterns with a slower editorial rhythm on desktop—without losing the shared terminology, product logic and familiar actions that make the platform feel consistent.</p></section>
      <section id="learning"><span>07 — What I learned</span><h2>Platform is context, not just screen size.</h2><ol><li>The same feature can need different design logic because attention, pace and intent change.</li><li>Borrowed patterns need a tone check; what feels playful elsewhere may feel cheap in a luxury context.</li><li>Focused testing produces sharper feedback than a broad, general review.</li></ol></section>
    </div>
  </div>
  <section className="case-next shell"><span>NEXT PROJECT</span><h2>Have a product problem worth solving?</h2><a className="pill" href="/contact">Let&apos;s talk <b>↗</b></a></section>
  <footer className="sub-footer shell">© 2026 AKSHAY VENKATA NARAYANA — PRODUCT DESIGNER / UX DESIGNER</footer>
</main>}
