import type {Metadata} from 'next';
import Link from 'next/link';

export const metadata:Metadata={title:'LUXTJ Case Study',description:'Turning complex luxury trip planning into one clear booking journey — an end-to-end LUXTJ product design case study.'};

const principles=[
  ['01','Preserve context','Travellers should always understand what they have chosen, what remains undecided and where they are in the journey.'],
  ['02','Reveal progressively','Show the information needed for the current decision without making users process the entire trip at once.'],
  ['03','Consequences first','Surface price, availability, policies and itinerary impact before the user commits.'],
  ['04','Design for recovery','A missed detail or changed plan should be easy to understand, edit and recover from.'],
];
const decisions=[
  {number:'01',title:'Keep the journey visible while users make decisions.',copy:'A persistent trip summary keeps dates, travellers, selections and running totals close to the decision being made. Users can review the whole journey without losing the page they are working on.',image:'/figma/case-3.png',note:'The tradeoff',trade:'Persistent context uses screen space, but it removes the much larger cost of memory, backtracking and avoidable uncertainty.'},
  {number:'02',title:'Make comparison feel calm, not crowded.',copy:'Filters and results were separated into a clear rhythm. The interface lets travellers narrow options, compare the meaningful differences and open detail without breaking the flow.',image:'/figma/case-10.png',note:'Why it matters',trade:'A luxury product should help people feel considered, not hurried. Strong hierarchy carries more value than showing every option at once.'},
  {number:'03',title:'Give hotels enough context to be chosen confidently.',copy:'Property cards connect imagery, location, package details, inclusions and price. The design answers the questions people ask before they need to open another page.',image:'/figma/case-14.png',note:'Designed for',trade:'Fast scanning first, deeper evidence second and a clear next action throughout.'},
  {number:'04',title:'Let the booking review work like a decision checkpoint.',copy:'The review page groups flights, stays, travellers and price into an understandable sequence. Changes remain available without turning the page into a settings screen.',image:'/figma/case-6.png',note:'Design intent',trade:'Users see consequences and totals before payment, with every part of the booking still traceable.'},
];
const supporting=[
  ['01','Traveller details','A repeatable form pattern supports one or several travellers, keeps validation local and makes incomplete information visible.','/figma/case-13.png'],
  ['02','Flight selection','Outbound and return choices share the same language, while duration, stops and fare conditions stay easy to compare.','/figma/case-4.png'],
  ['03','Hotel discovery','Filters, map context and content-rich results help people move from broad preference to a confident shortlist.','/figma/case-7.png'],
  ['04','Package confirmation','A clear booking state connects selected products, price and the next required action without hiding important detail.','/figma/case-12.png'],
];

function CaseHeader(){return <header className="case-header"><Link href="/" className="case-mini-id"><img src="/akshay-portrait.jpg" alt="Akshay"/><span><b>AKSHAY VENKATA NARAYANA</b><small>Product Designer | User Experience Designer</small></span></Link><a className="case-menu" href="/work" aria-label="Back to work">⌂</a></header>;}
function Kicker({children}:{children:React.ReactNode}){return <span className="case-kicker">{children}</span>;}

export default function LuxtjPage(){return <main className="case-page">
  <CaseHeader/>
  <section className="case-opening case-width reveal">
    <Kicker>PRODUCT DESIGN CASE STUDY · LUXTJ</Kicker>
    <h1>TURNING COMPLEX TRIP PLANNING INTO ONE<br/>CLEAR BOOKING JOURNEY.</h1>
    <p>I redesigned LUXTJ&apos;s booking experience across customer web and partner operations, turning flights, hotels, travellers and trip details into one connected journey that feels calm enough for premium travel.</p>
    <div className="case-facts"><div><small>ROLE</small><b>Lead Product Designer</b></div><div><small>FOCUS</small><b>End-to-end UX & UI</b></div><div><small>TIMELINE</small><b>12 months</b></div><div><small>COLLABORATION</small><b>Founder, product & engineering</b></div><div><small>ECOSYSTEM</small><b>Customer web + Extranet</b></div></div>
  </section>

  <section className="case-device-hero reveal"><img className="device-left" src="/figma/case-15.png" alt="LUXTJ extranet dashboard"/><img className="device-main" src="/figma/case-17.png" alt="LUXTJ travel website"/><img className="device-right" src="/figma/case-3.png" alt="LUXTJ trip review"/></section>

  <section className="case-section case-width snapshot reveal"><Kicker>A QUICK SNAPSHOT</Kicker><h2>I REDESIGNED THE JOURNEY, NOT JUST THE INTERFACE.</h2><p>The work connected inspiration, search, booking and partner fulfilment so that every step made the next one easier.</p><div className="snapshot-grid">{principles.slice(0,3).map(([n,t,c])=><article key={n}><b>{n}</b><h3>{t}</h3><p>{c}</p></article>)}</div></section>

  <section className="case-section case-width reveal"><Kicker>THE PRODUCT</Kicker><h2>A CONNECTED EXPERIENCE FROM INSPIRATION<br/>TO SUPPORT.</h2><p className="lead-copy">LUXTJ is a premium travel ecosystem. The design had to support a traveller&apos;s emotional journey and the operational journey behind it.</p><div className="glance-row">{['Inspire','Search','Decide','Review','Support'].map((x,i)=><article key={x}><small>0{i+1}</small><h3>{x}</h3><p>{['Editorial places and curated ideas','Flights, hotels and packages','Compare value and inclusions','Confirm travellers and totals','Booking changes and help'][i]}</p></article>)}</div></section>

  <section className="case-section case-width reveal"><Kicker>THE ECOSYSTEM</Kicker><h2>ONE TRAVEL IDEA. THREE CONNECTED PRODUCTS.</h2><p>Each surface has a different job, but the same product language and logic.</p><div className="ecosystem-grid"><article><img src="/figma/case-11.png" alt="LUXTJ mobile application"/><small>MOBILE APP</small><h3>Inspiration in the pocket</h3><p>Discover destinations, save ideas and return when the trip becomes real.</p></article><article className="ecosystem-dark"><img src="/figma/case-19.png" alt="LUXTJ web search"/><small>CUSTOMER WEBSITE</small><h3>Space to compare and plan</h3><p>Explore, evaluate and build a complex trip with more context.</p></article><article><img src="/figma/case-1.png" alt="LUXTJ partner extranet"/><small>EXTRANET</small><h3>Operations behind the promise</h3><p>Partners manage content, availability, pricing and bookings.</p></article></div></section>

  <section className="case-section case-width responsibility reveal"><div><Kicker>MY RESPONSIBILITY</Kicker><h2>FROM FRAMING<br/>THE PROBLEM TO A<br/>TO-BE EXPERIENCE.</h2></div><div className="responsibility-columns"><article><h3>PRODUCT THINKING</h3><p>Translated the mobile product into web journeys and identified where desktop behaviours created new opportunities.</p><h3>INFORMATION ARCHITECTURE</h3><p>Connected destinations, search, hotels, flights, Bucket List and Travel Calendar.</p></article><article><h3>UX & INTERACTION DESIGN</h3><p>Designed flows, selection patterns, information states, edge cases and responsive behaviour.</p><h3>DESIGN → DEVELOPMENT</h3><p>Worked with engineers to communicate behaviour, review builds and carry the design into production.</p></article></div></section>

  <section className="case-section case-width problem reveal"><Kicker>THE REAL PROBLEM</Kicker><h2>LUXURY TRAVEL IS NOT A LINEAR PURCHASE.</h2><p>People move between dreaming and deciding. They compare flights and stays, involve other travellers, revisit dates and change their minds. The experience needed to hold that complexity without feeling complicated.</p><blockquote><small>THE DESIGN QUESTION</small>How might we help travellers assemble a complex trip with confidence—without flattening the detail they genuinely need?</blockquote><div className="tension-grid"><article><b>Inspiration</b><span>↔</span><b>Action</b></article><article><b>Choice</b><span>↔</span><b>Confidence</b></article><article><b>Flexibility</b><span>↔</span><b>Clarity</b></article><article><b>Premium</b><span>↔</span><b>Practical</b></article></div></section>

  <section className="case-section case-width evidence reveal"><Kicker>FRAMING THE JOURNEY</Kicker><h2>WHAT I HEARD BECAME THE PRODUCT STRUCTURE.</h2><div className="evidence-grid"><article><small>TRAVELLERS SAID</small><h3>“I don&apos;t want to start over every time I compare.”</h3><p>Users needed the product to preserve context between search, details and review.</p></article><article><small>THE SYSTEM NEEDED</small><h3>A reliable source of truth for the trip.</h3><p>Selections, travellers, price and availability needed one consistent model.</p></article><article><small>THE BUSINESS NEEDED</small><h3>Confidence before conversion.</h3><p>Premium customers should understand the value of a choice before being asked to commit.</p></article></div></section>

  <section className="case-section case-width reveal"><Kicker>DESIGN PRINCIPLES</Kicker><h2>FOUR PRINCIPLES GUIDED THE WORK.</h2><div className="principle-grid">{principles.map(([n,t,c])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{c}</p></article>)}</div></section>

  <section className="case-section case-width architecture reveal"><Kicker>JOURNEY ARCHITECTURE</Kicker><h2>MAKE EVERY STEP ANSWER THE NEXT IMPORTANT QUESTION.</h2><div className="architecture-table"><div><b>BEFORE</b><b>QUESTION LEFT OPEN</b><b>DESIGN RESPONSE</b></div><div><span>Disconnected search screens</span><span>What have I already chosen?</span><span>Persistent trip context</span></div><div><span>Dense result cards</span><span>What makes this right for me?</span><span>Progressive information hierarchy</span></div><div><span>Totals appear late</span><span>What will this decision cost?</span><span>Running price and consequences</span></div><div><span>Errors at submission</span><span>How do I recover?</span><span>Inline validation and editable review</span></div></div></section>

  <section className="case-section case-width reveal"><Kicker>CORE DESIGN DECISIONS</Kicker><h2>FOUR DECISIONS CARRIED MOST<br/>OF THE PRODUCT RISK.</h2><div className="decision-list">{decisions.map((item,index)=><article className={`decision decision-${index+1}`} key={item.number}><div className="decision-copy"><span>{item.number}</span><h3>{item.title}</h3><p>{item.copy}</p><small>{item.note}</small><strong>{item.trade}</strong></div><div className="decision-media"><img src={item.image} alt={item.title}/></div></article>)}</div></section>

  <section className="case-section case-width reveal"><Kicker>BEYOND BOOKING</Kicker><h2>HELPING TRAVELLERS MOVE FROM<br/>“SOMEDAY” TO A SEASONABLE TRIP.</h2><p>The Bucket List and Travel Calendar bridge inspiration and intent. They let people save places before they know the details, then return when timing makes the trip possible.</p><div className="beyond-grid"><article><img src="/figma/case-5.png" alt="LUXTJ mobile Bucket List"/><h3>Bucket List</h3><p>Save a destination without forcing a date or decision too early.</p></article><article><img src="/figma/case-18.png" alt="LUXTJ travel calendar"/><h3>Travel Calendar</h3><p>Turn saved intent into visible upcoming journeys and planning actions.</p></article></div></section>

  <section className="case-section case-width reveal"><Kicker>SUPPORTING JOURNEYS</Kicker><h2>THE SMALL STATES CARRY REAL PRODUCT RISK.</h2><div className="supporting-grid">{supporting.map(([n,t,c,img])=><article key={n}><img src={img} alt={t}/><span>{n}</span><h3>{t}</h3><p>{c}</p></article>)}</div></section>

  <section className="case-section case-width system reveal"><Kicker>REUSABLE INTERACTION LANGUAGE</Kicker><h2>REPETITION BECAME A SYSTEM.</h2><p>Cards, filters, selection states, summaries and actions repeat across the product so the next journey feels familiar before it begins.</p><div className="system-board"><img src="/figma/case-16.png" alt="LUXTJ reusable design patterns"/><img src="/figma/case-20.png" alt="LUXTJ website design system"/></div></section>

  <section className="case-section case-width validation reveal"><Kicker>VALIDATION & ITERATION</Kicker><h2>I TESTED THE DECISIONS CARRYING THE MOST RISK.</h2><div className="validation-grid"><article><b>RISK</b><h3>Would users understand a trip as one connected object?</h3><p>Sessions focused on whether people could move between products without losing their mental model.</p></article><article><b>DESIGN RESPONSE</b><h3>Strengthen persistent context.</h3><p>Trip summaries, states and language were made consistent across the journey.</p></article><article><b>MEASURE AFTER LAUNCH</b><h3>Completion, recovery and confidence.</h3><p>Track booking completion, edit loops, support demand and where users pause.</p></article></div><div className="iteration-strip"><span>Test the uncertain state</span><i>→</i><span>Observe hesitation</span><i>→</i><span>Clarify the decision</span><i>→</i><span>Retest in context</span></div></section>

  <section className="case-section case-width outcomes reveal"><Kicker>OUTCOMES</Kicker><h2>WHAT CHANGED BECAUSE OF THE REDESIGN.</h2><div className="outcome-grid"><article><small>FOR TRAVELLERS</small><h3>A more coherent path from discovery to review.</h3><p>Less memory work, clearer consequences and more confidence in complex decisions.</p></article><article><small>FOR THE PRODUCT</small><h3>One interaction language across mobile and web.</h3><p>Shared patterns connect the ecosystem and create room for new journeys.</p></article><article><small>FOR DELIVERY</small><h3>A clearer system for implementation.</h3><p>Reusable behaviour and states reduce ambiguity between design and engineering.</p></article></div></section>

  <section className="case-section case-width tradeoffs reveal"><Kicker>TRADEOFFS</Kicker><h2>WHAT I DELIBERATELY CHOSE NOT TO SIMPLIFY.</h2><div className="tradeoff-table"><div><b>DECISION</b><b>BENEFIT</b><b>COST ACCEPTED</b></div><div><span>Keep a visible trip summary</span><span>Continuity and confidence</span><span>Less space for content</span></div><div><span>Retain meaningful fare and policy detail</span><span>Better decisions before commitment</span><span>More information to structure</span></div><div><span>Support editing during review</span><span>Recovery without restarting</span><span>Additional states and engineering effort</span></div></div></section>

  <section className="case-section case-width reflection reveal"><Kicker>REFLECTION</Kicker><h2>TURN THE DESIGN HYPOTHESIS INTO PRODUCT EVIDENCE.</h2><div className="reflection-grid"><article><h3>What I would measure next</h3><ul><li>Search-to-detail and detail-to-selection conversion</li><li>Where travellers edit or abandon a journey</li><li>Time spent comparing before a confident selection</li><li>Support questions after booking review</li></ul></article><article><h3>What I would explore next</h3><ul><li>More useful personalisation from saved intent</li><li>Shared planning for multiple travellers</li><li>Smarter recovery when availability changes</li><li>Extranet signals that improve customer confidence</li></ul></article></div></section>

  <section className="case-closing case-width reveal"><Kicker>THE PRINCIPLE I&apos;LL CARRY FORWARD</Kicker><h2>PREMIUM TRAVEL DOES NOT FEEL EFFORTLESS<br/>BECAUSE COMPLEXITY DISAPPEARS.</h2><p>It feels effortless because the product reveals the right complexity at the right moment.</p><div><a href="/work">← All case studies</a><a href="/contact">Start a conversation ↗</a></div></section>
  <footer className="case-footer">© 2026 AKSHAY VENKATA NARAYANA — PRODUCT DESIGNER / UX DESIGNER</footer>
</main>}
